import gillAttributeBufferMapFactory  from "app/gill/attribute-buffer-map/factory";
import gillAttributeValueMapFactory   from "app/gill/model/attribute-value-map/factory";
import gillBufferFactory              from "app/gill/buffer/factory";
import gillBufferCache                from "app/gill/buffer-cache";
import gillContextModelsMapFactory    from "app/gill/context-models-map/factory";
import gillModelBufferMapFactory      from "app/gill/model-buffer-map/factory";
import gillChangedAttributeMapFactory from "app/gill/model/changed-attribute-map/factory";
import gillIndexCollectionFactory     from "app/gill/model/index-collection/factory";
import gillModelFactory               from "app/gill/model/factory";
import gillNumberFactory              from "app/gill/model/number/factory";
import gillProgramService             from "app/gill/program/service";
import gillProgramSourceFactory       from "app/gill/program/source/factory";
import gillUniformValueMapFactory     from "app/gill/model/uniform-value-map/factory";
import gillVector2Factory             from "app/gill/model/vector2/factory";
import gillVector3Factory             from "app/gill/model/vector3/factory";
import gillVertexCollectionFactory    from "app/gill/model/vertex/collection/factory";
import gillVertexFactory              from "app/gill/model/vertex/factory";

(<any>window).gillAttributeBufferMapFactory   = gillAttributeBufferMapFactory;
(<any>window).gillAttributeValueMapFactory    = gillAttributeValueMapFactory;
(<any>window).gillBufferFactory               = gillBufferFactory;
(<any>window).gillBufferCache                 = gillBufferCache;
(<any>window).gillContextModelsMapFactory     = gillContextModelsMapFactory;
(<any>window).gillModelBufferMapFactory       = gillModelBufferMapFactory;
(<any>window).gillChangedAttributeMapFactory  = gillChangedAttributeMapFactory;
(<any>window).gillIndexCollectionFactory      = gillIndexCollectionFactory;
(<any>window).gillModelFactory                = gillModelFactory;
(<any>window).gillNumberFactory               = gillNumberFactory;
(<any>window).gillProgramService              = gillProgramService;
(<any>window).gillProgramSourceFactory        = gillProgramSourceFactory;
(<any>window).gillUniformValueMapFactory      = gillUniformValueMapFactory;
(<any>window).gillVector2Factory              = gillVector2Factory;
(<any>window).gillVector3Factory              = gillVector3Factory;
(<any>window).gillVertexCollectionFactory     = gillVertexCollectionFactory;
(<any>window).gillVertexFactory               = gillVertexFactory;
